### ISSUE TITLE
Make dmm work for magit-status-mode

### ISSUE THREAD

**Issue by itsjeyd** [steckerhalter/discover-my-major#3]
When I try to invoke `discover-my-major` from a `magit` status buffer, the window that pops up is empty and I get the following message in the echo area:

> Key sequence j f starts with non-prefix key j

This is after invoking Emacs via `emacs -Q`.

It would be great if this could be fixed somehow. Would love to be able to use `dmm` with `magit-status-mode` :)

**Comment by steckerhalter** [comment]
the makey library is currently not compatible with the keys used by magit-status-mode, it would have to be fixed there if possible
