### ISSUE TITLE
Recommended keybinding is already taken

### ISSUE THREAD

**Issue by Hasimir** [steckerhalter/discover-my-major#4]
Heya, just a quick FYI since it was probably just overlooked.  From section 10.9 of the manual (help files):

    `C-h C-m'
         Display information about ordering printed copies of Emacs manuals
         (`view-order-manuals').

I get that you wanted something similar to C-h m, but you'll probably need to find something different or warn that setting this key sequence might not be what people want in all cases.  As for myself, I've put it on one of the function keys because it makes for a very nice cheat sheet, but that too won't be for everyone.

Aside from that, damned brilliant little feature this one.  Cheers!  :)

**Comment by steckerhalter** [comment]
Thanks for the hint. I have made a note about that in the README
