### ISSUE TITLE
Filter keybinding on keypress

### ISSUE THREAD

**Issue by jeekl** [steckerhalter/discover-my-major#6]
It would be awesome if I can filter the shown keybindings by pressing a key.

I run `M-x discover-my-major`. List with keybinds pop up. I press `C-c` and the list now only shows the keybinds that contain `C-c`.

**Comment by steckerhalter** [comment]
I think that would need some work in the makey library (https://github.com/mickeynp/makey). I currently have other priorities so feel free to hack on it...

**Comment by ardumont** [comment]
Hello,

> I press C-c and the list now only shows the keybinds that contain C-c.

This [mode](https://github.com/kai2nenobu/guide-key) can already do that.
Granted, it will display all runtime bindings (not only the major mode).

Cheers,

**Comment by steckerhalter** [comment]
Currently dmm is static. This feature would involve quite some changes and I'm not sure if it is even of much use since usually all the bindings are already visible. Feel free to submit a PR if you want the feature to be added though.
