### ISSUE TITLE
empty make-key buffer on go-mode

### ISSUE THREAD

**Issue by gozes** [steckerhalter/discover-my-major#9]
when I call discover-my-major on a go-mode buffer the buffer that  pops up is empty. 

you can see how I have it setup here https://github.com/gozes/.emacs.d/blob/master/config.org#discover-my-major 

for my go-mode setup see here

https://github.com/gozes/.emacs.d/blob/master/config.org#go

**Comment by steckerhalter** [comment]
see issue #3 

the makey library doesn't support this kind of prefix key: `Key sequence C-c C-g a starts with non-prefix key C-c C-g`

it would have to be fixed in makey itself so you might open an issue there

**Comment by xiongtx** [comment]
See #10.

**Comment by steckerhalter** [comment]
merged the PR. closing since it works now also with go-mode. thanks for the fix
